package com.creatoros.social.integration.instagram;

import com.creatoros.content.ContentType;
import com.creatoros.social.Platform;
import com.creatoros.social.integration.ConnectedAccount;
import com.creatoros.social.integration.PlatformContentItem;
import com.creatoros.social.integration.PlatformPerformanceSnapshot;
import com.creatoros.social.integration.PlatformProfile;
import com.creatoros.social.integration.SocialConnectRequest;
import com.creatoros.social.integration.SocialPlatformClient;
import com.creatoros.social.integration.mock.ContentGrowthModel;
import java.time.Duration;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import org.springframework.stereotype.Component;

/**
 * <b>Demo/mock implementation.</b> The Instagram Graph API requires Meta App
 * Review and a connected Instagram Business/Creator account owned by the app
 * before it will return real insights, which is not obtainable for a student
 * portfolio project. Rather than fake a "real" integration, this adapter is
 * clearly labeled as demo data and implements the exact same
 * {@link SocialPlatformClient} boundary as the real YouTube adapter.
 *
 * <p>To swap in the real Graph API once app review is granted: implement
 * OAuth (Instagram Login), call {@code GET /{ig-user-id}/media} for content
 * and {@code GET /{media-id}/insights} for performance, and replace this
 * {@code @Component} registration - no other code in the application needs to
 * change, since everything upstream depends only on {@link SocialPlatformClient}.
 */
@Component
public class InstagramSocialPlatformClient implements SocialPlatformClient {

    private static final ContentType[] TYPES = {ContentType.REEL, ContentType.POST, ContentType.STORY};
    private static final String[] TITLES = {
            "Reel: behind the scenes 🎬", "Carousel: 5 things I learned this week",
            "Story highlight: Q&A", "Reel: outfit transition", "Post: collab announcement",
            "Reel: day in my life", "Post: milestone thank you", "Story: poll results"
    };

    @Override
    public Platform platform() {
        return Platform.INSTAGRAM;
    }

    @Override
    public PlatformProfile fetchAccountProfile(SocialConnectRequest request) {
        String handle = request.handle() != null && !request.handle().isBlank() ? request.handle() : "demo.creator";
        return new PlatformProfile(handle, "@" + handle, "(Demo) " + handle);
    }

    @Override
    public List<PlatformContentItem> fetchContent(ConnectedAccount account) {
        List<PlatformContentItem> items = new ArrayList<>();
        Instant now = Instant.now();
        for (int i = 0; i < TITLES.length; i++) {
            Instant publishedAt = now.minus(Duration.ofDays(1 + (long) (i * 2.3)));
            items.add(new PlatformContentItem(
                    contentId(account, i),
                    "[DEMO] " + TITLES[i],
                    "Demo content generated by the Instagram mock adapter (real Graph API requires Meta App Review).",
                    TYPES[i % TYPES.length],
                    publishedAt,
                    TYPES[i % TYPES.length] == ContentType.REEL ? 25 + (i * 3) : null,
                    "en",
                    i % 2 == 0 ? "US" : "IN",
                    "Lifestyle",
                    null
            ));
        }
        return items;
    }

    @Override
    public List<PlatformPerformanceSnapshot> fetchPerformance(ConnectedAccount account, List<String> platformContentIds) {
        Instant now = Instant.now();
        List<PlatformPerformanceSnapshot> snapshots = new ArrayList<>();
        for (int i = 0; i < TITLES.length; i++) {
            String id = contentId(account, i);
            if (!platformContentIds.contains(id)) {
                continue;
            }
            Instant publishedAt = now.minus(Duration.ofDays(1 + (long) (i * 2.3)));
            var model = new ContentGrowthModel(account.id() + ":" + id);
            double hours = ChronoUnit.MINUTES.between(publishedAt, now) / 60.0;
            snapshots.add(new PlatformPerformanceSnapshot(
                    id, now,
                    model.viewsAt(hours), model.likesAt(hours), model.commentsAt(hours), model.sharesAt(hours),
                    model.followersAttributedAt(hours), null, null,
                    model.regionBreakdownAt(hours)
            ));
        }
        return snapshots;
    }

    private String contentId(ConnectedAccount account, int index) {
        return "ig-demo-" + account.id() + "-" + index;
    }
}
