package com.creatoros.social.integration.mock;

import com.creatoros.social.Platform;
import com.creatoros.social.integration.ConnectedAccount;
import com.creatoros.social.integration.PlatformContentItem;
import com.creatoros.social.integration.PlatformPerformanceSnapshot;
import com.creatoros.social.integration.PlatformProfile;
import com.creatoros.social.integration.SocialConnectRequest;
import com.creatoros.social.integration.SocialPlatformClient;
import java.time.Duration;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import org.springframework.stereotype.Component;

/**
 * Deterministic demo/mock implementation of {@link SocialPlatformClient}. Used
 * when a user connects a {@code MOCK} platform account, or by the demo data
 * generator. All data returned here is clearly synthetic - see docs/architecture.md
 * "Why mock unsupported social APIs?" for why this exists instead of scraping
 * Instagram/TikTok/etc.
 */
@Component
public class MockSocialPlatformClient implements SocialPlatformClient {

    @Override
    public Platform platform() {
        return Platform.MOCK;
    }

    @Override
    public PlatformProfile fetchAccountProfile(SocialConnectRequest request) {
        String handle = request.handle() != null && !request.handle().isBlank()
                ? request.handle() : "demo-creator";
        return new PlatformProfile(handle, "@" + handle, "Demo Creator (" + handle + ")");
    }

    @Override
    public List<PlatformContentItem> fetchContent(ConnectedAccount account) {
        List<PlatformContentItem> items = new ArrayList<>();
        Instant now = Instant.now();
        var templates = MockContentCatalog.TEMPLATES;
        for (int i = 0; i < templates.length; i++) {
            var t = templates[i];
            Instant publishedAt = now.minus(Duration.ofDays(1 + (long) (i * 1.7)))
                    .minus(Duration.ofHours(i % 7));
            items.add(new PlatformContentItem(
                    contentId(account, i),
                    t.title(),
                    "Demo content generated by the MOCK platform adapter.",
                    t.type(),
                    publishedAt,
                    t.durationSeconds() > 0 ? t.durationSeconds() : null,
                    "en",
                    regionFor(account, i),
                    t.category(),
                    null
            ));
        }
        return items;
    }

    @Override
    public List<PlatformPerformanceSnapshot> fetchPerformance(ConnectedAccount account, List<String> platformContentIds) {
        Instant now = Instant.now();
        List<PlatformPerformanceSnapshot> snapshots = new ArrayList<>();
        var templates = MockContentCatalog.TEMPLATES;
        for (int i = 0; i < templates.length; i++) {
            String id = contentId(account, i);
            if (!platformContentIds.contains(id)) {
                continue;
            }
            Instant publishedAt = now.minus(Duration.ofDays(1 + (long) (i * 1.7))).minus(Duration.ofHours(i % 7));
            var model = new ContentGrowthModel(account.id() + ":" + id);
            double hours = ChronoUnit.MINUTES.between(publishedAt, now) / 60.0;
            snapshots.add(new PlatformPerformanceSnapshot(
                    id,
                    now,
                    model.viewsAt(hours),
                    model.likesAt(hours),
                    model.commentsAt(hours),
                    model.sharesAt(hours),
                    model.followersAttributedAt(hours),
                    Math.round(model.viewsAt(hours) * model.avgViewDurationSeconds(
                            templates[i].durationSeconds() > 0 ? templates[i].durationSeconds() : 30)),
                    model.avgViewDurationSeconds(templates[i].durationSeconds() > 0 ? templates[i].durationSeconds() : 30),
                    model.regionBreakdownAt(hours)
            ));
        }
        return snapshots;
    }

    private String contentId(ConnectedAccount account, int index) {
        return "mock-" + account.id() + "-" + index;
    }

    private String regionFor(ConnectedAccount account, int index) {
        String[] regions = {"US", "IN", "GB", "BR", "NG"};
        return regions[Math.floorMod(account.id().hashCode() + index, regions.length)];
    }
}
